/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anup Jacob
 */

import java.sql.*;
import javax.swing.*;

public class Addrem extends javax.swing.JFrame {

    /**
     * Creates new form Addrem
     */
    int editbtn;
    int stid;
    public Addrem() {
        initComponents();
        editbtn=0;
   
        for (int i=2019; i<2042; i++)
        {
            String y= Integer.toString(i);
            yy.addItem(y);
        }
    }
    public Addrem(int s){
         initComponents();
         editbtn=1;
         stid=s;
         for (int i=2019; i<2042; i++)
        {
            String y= Integer.toString(i);
            yy.addItem(y);
        }
         System.out.println(s);
         System.out.println("inadd rem");
         try{
             String url="jdbc:derby://localhost:1527/remainderdb";
            String uname="admin1";
            String password="admin";
            
            Connection con =DriverManager.getConnection(url, uname, password);
            Statement stmt = con.createStatement();
            String query="SELECT TDATE,TTIME,NOTES FROM ADMIN1.TREMAINDER WHERE TID="+s+"";
            ResultSet rs = stmt.executeQuery(query);
            System.out.println("hai");
            String darray[]=null;
            String dtime[]=null;
            if(rs.next()){
                String date=rs.getString(1);
                System.out.println(date);
                darray=date.split("-");
                for(int i=0;i<3;i++){
                    System.out.println("daaray"+darray[i]);
                }
                for(int i=0;i<Dd.getItemCount();i++){
                    if(Dd.getItemAt(i).equals(darray[2])){
                        Dd.setSelectedIndex(i);
                        break;
                    }
                }
                for(int i=0;i<mm.getItemCount();i++){
                    if(mm.getItemAt(i).equals(darray[1])){
                        mm.setSelectedIndex(i);
                        break;
                    }
                }
                for(int i=0;i<yy.getItemCount();i++){
                    if(yy.getItemAt(i).equals(darray[0])){
                        yy.setSelectedIndex(i);
                        break;
                    }
                }
              
                String ttime =rs.getString(2);
                System.out.println("Time"+ttime);
                dtime=ttime.split(":");
                for(int i=0;i<3;i++){
                    System.out.println("time"+dtime[i]);
                }
                for(int i=0;i<hh.getItemCount();i++){
                    if(hh.getItemAt(i).equals(dtime[0])){
                        hh.setSelectedIndex(i);
                        break;
                    }
                }
                for(int i=0;i<min.getItemCount();i++){
                    if(min.getItemAt(i).equals(dtime[1])){
                        min.setSelectedIndex(i);
                        break;
                    }
                }
                for(int i=0;i<sec.getItemCount();i++){
                    if(sec.getItemAt(i).equals(dtime[2])){
                        sec.setSelectedIndex(i);
                        break;
                    }
                }
                Remtxt.setText(rs.getString(3));
             
            }
             
         }
         catch(SQLException e){
             JOptionPane.showMessageDialog(null, e.toString());
             
         }
         
         
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Dd = new javax.swing.JComboBox<>();
        mm = new javax.swing.JComboBox<>();
        yy = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        hh = new javax.swing.JComboBox<>();
        min = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Remtxt = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        sec = new javax.swing.JComboBox<>();

        setResizable(false);

        jLabel1.setText("Date");

        Dd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel2.setText("Time");

        hh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        min.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));

        jLabel3.setText("Remainder");

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        sec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Remtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SaveBtn)
                        .addGap(18, 18, 18)
                        .addComponent(CancelBtn)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Remtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBtn)
                    .addComponent(CancelBtn))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        try{
            String url="jdbc:derby://localhost:1527/remainderdb";
            String uname="admin1";
            String password="admin";
            
            
            Connection con =DriverManager.getConnection(url, uname, password);
            Statement stmt = con.createStatement();
           
            String date="";
            String cdd= Dd.getSelectedItem().toString();
            String cmm= mm.getSelectedItem().toString();
            String cyy=yy.getSelectedItem().toString();
            date=cyy+"-"+cmm+"-"+cdd;
            
            //System.out.print(date);
            
            String time="";
            String chh= hh.getSelectedItem().toString();
            String cmin= min.getSelectedItem().toString();
            String csec=sec.getSelectedItem().toString();
            time=chh+":"+cmin+":"+csec;
            
            String notes= Remtxt.getText();
            if(editbtn==0)
            {
            String query = "INSERT INTO ADMIN1.TREMAINDER (TDATE,TTIME,NOTES) VALUES ('"+date+"','"+time+"','"+notes+"')";
            stmt.execute(query);
            //JOptionPane.showMessageDialog(null, "Remainder added");
            }
            if(editbtn==1)
            {
                
                PreparedStatement ps=con.prepareStatement("UPDATE ADMIN1.TREMAINDER SET TDATE=?,TTIME=?,NOTES=? WHERE TID="+stid+" ");
                ps.setString(1, date);
                ps.setString(2,time);
                ps.setString(3, notes);
                ps.executeUpdate();
                System.out.println("DATE"+date+"time"+time+"notes"+notes+"edit done");
            }
            
            new Remainder().setVisible(true);
            this.setVisible(false);
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }   
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_CancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addrem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addrem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addrem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addrem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addrem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JComboBox<String> Dd;
    private javax.swing.JTextField Remtxt;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JComboBox<String> hh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> min;
    private javax.swing.JComboBox<String> mm;
    private javax.swing.JComboBox<String> sec;
    private javax.swing.JComboBox<String> yy;
    // End of variables declaration//GEN-END:variables
}
